config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  

 root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
validates :title, presence: true, length: { minimum: 3, maximum: 50 }
validates :description, presence: true, length: { minimum: 10, maximum: 300 }
validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save {self.email=email.downcase}
    validates :username, presence: true,
               uniqueness: { case_sensitive: false }, 
               length:{minimum: 3,maximum: 25}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence:true,length: {maximum: 105},
               uniqueness:{case_sensitive:false},
               format: {with: VALID_EMAIL_REGEX}
       has_secure_password        
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
     !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger] = "you must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_articles, only: [:edit , :update , :show , :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    # def index
    # #    render :partial => "show"
    # @article = Article.where(knowledge: 'Learning').first
    # end
            def index 
                @articles = Article.paginate(page: params[:page], per_page: 5)
            end
            def show
                    # render plain: @article.title
                end
            def new
                @article = Article.new
            end
            def edit
                @article =Article.find(params[:id])
            end
                def update
                    if @article.update(article_params)
                    flash[:success]="Article is successfully updates"
                    redirect_to articles_path(@article)
                    else
                        render 'edit'
                end
            end
            def destroy
                 @article.destroy
                 flash[:danger]="Article is fully deleted"
                 redirect_to articles_path
            end
            def create
                @article = Article.new(article_params)
                @article.user = current_user
                if @article.save
                    #do something
                    flash[:success] ="Article is successfully created"
                    redirect_to articles_path(@article)
                else
                    render 'new'
                end
            end 
            private
            def set_articles
                @article = Article.find(params[:id])
            end
            def require_same_user
                if current_user != @article.user and !current_user.admin?
                    flash[:danger] = "you can only edit or delete your own article"
                    redirect_to root_path
                end
            end
            private 
            def article_params
                params.require(:article).permit(:title, :description)
            end
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    def create
        user =  User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "you have successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] ="There was something wrong with your login information"
            render 'new'
        end
    end
    def destroy
       session[:user_id] = nil
       flash[:success] = "you have logged in"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if  @user.save
            session[:user_id] = @user.id
            flash[:success]="Welcome to the alph blog #{@user.username}"
            redirect_to articles_path(@user)
        else
            render 'new'
        end
    end
    def edit
       
    end
    def update
      
        if @user.update(user_params)
            flash[:success] = "your account is updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    def show
     
        @user_articles = @user.articles.paginate(page: params[:page], per_page:3)
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and article created by user have been deleted"
        redirect_to users_path
    end
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    def set_user
        @user = User.find(params[:id])
    end
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "you can only edit your own account"
            redirect_to root_path
        end
    end
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "only admin user can perform the action"
            redirect_to root_path
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
       gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
       size = options[:size]
       gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="card">
        <div class="col-xs-8 col-xs-offset-2">
                  <div class="well well-lg">
                          <div class="card-header">
                              <%= link_to article.title, article_path(article) %>
                            </div>
                            <div class="card-body">
                                  <%= truncate(article.description, length: 100) %>
                                  <div class="card-meta-details">
                                  <small>Created by: <%= article.user.username if article.user %>,
                                  <%= time_ago_in_words(article.created_at) %> ago,
                                  last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                                  </div>
                            </div>
                            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                                    <div class="card-actions">
                                        <%= link_to "Edit the article", edit_article_path(article) , class: "btn btn-primary" %>

                                  
                                        <%= link_to "Delete the article", article_path(article), method: :delete , 
                                                      data: {confirm: "Are you sure ,you want to delete the article", class: "btn btn-danger"} %>
                                      </div>
                            <% end %>
                  </div>
       </div>
</div>
  <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>
<div class= 'row'>
   <div class='col-xs-12'>
                <%= form_for(@article, :html => {class:"form", role: "form"}) do |f| %> 
                                <div class="form group row">
                                                <div class="col-sm-2 col-form-label">
                                                        
                                                        <%= f.label :title %>
                                                </div>
                                                <div class='col-sm-10'>
                                                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                                                </div>
                                </div>           
                                <div class="form group row">
                                        <div class="col-sm-6 col-form-label">
                                                <%= f.label :description %>
                                        </div>
                                        <div class='col-sm-6 '>
                                                <%= f.text_area :description,rows: 10,cols: 50,  class: "form-control", placeholder: "Description of article", autofocus: true %>
                                        </div>
                                </div>      
                                        
                                        <div class="form group row">
                                               <div class="col-sm-offset-2 col-sm-8">
                                                   <%= f.submit class:'btn btn-primary btn-md ' %>
                                                </div>
                                        </div>
                <% end %>
                        <div class="col-xs-4 col-xs-offset-4">
                                [  <%= link_to "cancel request and return to article listing" , articles_path %> ]
                        </div>
        </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>


  <%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center"> All listing page</h1>
  <div class="pagination">
      <%= will_paginate %>
  </div>
  <%= render 'article', obj: @articles %>
  <div class="pagination">
      <%= will_paginate %>
  </div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

  <%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title:<%= @article.title %></h2>

<% if @article.user %>
   <div class="well col-xs-8 col-xs-offset-2">
     <ul class="listing">
                <div class="card text-center">
                    <div class="well col-md-4 col-md-offset-4">
                       
                            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                            <li class="card-header">
                                <%= link_to @article.user.username, user_path(@article.user) %>
                            </li>
                            <li><small><%= pluralize(@article.user.articles.count , "article") if @article.user.articles %>
                            </small></li>
                    </div>
                </div>
            </ul>
    <% end %>
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <h3 align="center"><%= simple_format(@article.description) %></h3>
   <div class="article-actions">
   <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit the article", edit_article_path(@article) , class: "btn btn-primary" %>

             
           <%= link_to "Delete the article", article_path(@article), method: :delete , 
                                data: {confirm: "Are you sure ,you want to delete the article", class: "btn btn-danger"} %>
     <% end %>                           
            <%= link_to  "View all article", article_path, class: "btn btn-xs btn-success" %>
             </div>
        </div>

app/views/layouts/_footer.html.erb
<div class="container">
	<section id="footer">
		<div class="container">
			<nav>
				
				
						
                        <%= link_to "About" ,about_path ,class: "fa fa-angle-double-right" %> 
				

			</nav>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
				</hr>
			</div>	
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p><u><a href="https://www.nationaltransaction.com/">National Transaction Corporation</a></u> is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]</p>
					<p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Sunlimetech</a></p>
				</div>
				</hr>
			</div>	
		</div>
	</section>
    </div>

app/views/layouts/_messages.erb
  <% flash.each do | name, msg| %>
     <ul>
          <li><%= msg %></li>
     </ul>
  <% end %>
  

app/views/layouts/_messages.html.erb
 <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
            <% flash.each do | name, msg| %>
              <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215</a>
                  <%= content_tag :div , msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
            <% end %>
      </div>
 </div>    
  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
   <%= link_to  "Alpha-blogs", root_path, class: "navbar-barand" , id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <a class="nav-link">  <%= link_to "Articles" ,articles_path %> </a>
      </li>
      <li>
        <a class="nav-link">  <%= link_to "Users" , users_path %> </a>
      </li>
        
        <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         
          <a><%= link_to  "New Article" , new_article_path %></a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% end %>
      
    </ul>
     <ul class="navbar-nav mr-auto">
         <li class="nav-item">
              <% if  logged_in? %>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
             
            </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Your profile <%= "Admin" if current_user.admin? %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item"><%= link_to "Edit your profile", edit_user_path(current_user) %></a>
         <a class="dropdown-item"><%= link_to "View your profile", user_path(current_user) %></a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
       <% else %>
               <li><%= link_to 'Login', login_path %></li>
                <li><%= link_to 'sign up', signup_path %></li>
                <% end %>
     </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
         <div class="col-xs-8 col-xs-offset-2">
                <div class="list-group-item list-group-item-danger">
                                        <div class="list-heading"> 
                                                        <h2 class="list-title">
                                                                <%= pluralize(obj.errors.count,"error") %>
                                                                :prohibited this article for error display
                                                        </h2>
                                                        <div class="list-body">
                                                                <ul>
                                                                        <% obj.errors.full_messages.each do |msg| %>
                                                                        <li>
                                                                                <%= msg %>
                                                                        </li>
                                                                        <% end %>
                                                                </ul>
                                                        </div> 
                                        </div>   
                </div>
       </div>
 </div>               
          
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>
<div class= 'row'>
   <div class='col-xs-12'>
                <%= form_for(@user, :html => {class:"form", role: "form"}) do |f| %> 
                                <div class="form group row">
                                                <div class="col-sm-4 col-form-label">
                                                        
                                                        <%= f.label :username %>
                                                </div>
                                                <div class='col-sm-10'>
                                                <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                                                </div>
                                </div>           
                                <div class="form group row">
                                        <div class="col-sm-6 col-form-label">
                                                <%= f.label :email %>
                                        </div>
                                        <div class='col-sm-6 '>
                                                <%= f.email_field :email,  class: "form-control", placeholder: "Enter an email", autofocus: true %>
                                        </div>
                                </div> 
                                  <div class="form group row">
                                        <div class="col-sm-6 col-form-label">
                                                <%= f.label :password %>
                                        </div>
                                        <div class='col-sm-6 '>
                                                <%= f.password_field :password, class: "form-control",type:"password", placeholder: "Enter password", autofocus: true %>
                                        </div>
                                </div>        
                                        
                                        <div class="form group row">
                                               <div class="col-sm-offset-2 col-sm-8">
                                                   <%= f.submit(@user.new_record? ? "Sign up" : "update account", class:'btn btn-primary btn-md ') %>
                                                </div>
                                        </div>
                <% end %>
                        <div class="col-xs-4 col-xs-offset-4">
                                [  <%= link_to "cancel request and return to article listing" , articles_path %> ]
                        </div>
        </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center"> all alpha bloggers</h1>

<div align="center">
<div class="pagination">
      <%= will_paginate %>
  </div>
        <%= @users.each do |user| %>
            <ul class="listing">
                <div class="card text-center">
                    <div class="well col-md-4 col-md-offset-4">
                    
                            <li><%= link_to gravatar_for(user), user_path(user) %></li>
                            <li class="card-header">
                                <%= link_to user.username, user_path(user) %>
                            </li>
                            <li><small><%= pluralize(user.articles.count , "article") if user.articles %></small></li>
                            <% if logged_in? and current_user.admin? %>
                            <li><%= link_to "Delete this user", user_path(user), method: :delete,
                                   data:{ confirm:"Are you delete the users and all their articles"} %>
                                   </li>
                                   <% end %>
                    </div>
                </div>
            </ul>
        <% end %>
        <div class="pagination">
      <%= will_paginate %>
  </div>
</div>
 
 

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> welcome to <%= @user.username %>'s page</h1>
 <div class ="row">
 <li>Created by:</li>
    <div class="rounded mx-auto d-block">
        <%= gravatar_for @user,size:150 %>
    </div>
 </div>
 <h4 align="center"><%= @user.username %>'s articles</h4>   
 <div class="center">
    <%= will_paginate @user_articles %>
 </div>
 <%= render 'articles/article', obj: @user_articles %>
 <div class="center">
    <%= will_paginate @user_articles %>
 </div>

app/views/welcome/about.html.erb
<h1>this is the homepage of my blogs</h1>

<%= link_to 'Home',root_path %>

app/views/welcome/home.html.erb
<div class ="center jumbotron">
   <h1> ALPHA-BLOG </h1>
   <%= link_to "signup-now" ,signup_path ,class: "btn btn-success btn-lg btn-xlarge" %>
</div>